server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;

    index index.php ui.html;

    # Отдача ui.html напрямую как статика
    location /ui.html {
        try_files $uri =404;
    }

    # Отдача любых статических файлов (css, js, html)
    location /static/ {
        alias /var/www/html/public/static/;
    }

    # Все остальные запросы проксируются на index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }
}
